### ISSUE TITLE
Question: pasting from the clipboard

### ISSUE THREAD

**Issue by arthurnn** [rejeep/ruby-end.el#14]
Not sure if it is ok to ask questions about ruby-end here, also dunno if thats a bug or not.
The case is: if I copy a ruby method(for instance), and I paste it in another buffer(with ruby-end minor mode enabled). It will do the right thing if I only used the killring, but if I copy from a website, and paste it to emacs, ruby-end will add a bunch of `end`, even if they are not necessary. 
Not sure if you saw this before. Can we do something about that?

thanks

**Comment by rejeep** [comment]
What do you mean by "a bunch of end"?

**Comment by arthurnn** [comment]
> What do you mean by "a bunch of end"?

Sorry, what I meant was. If I copy this from a browser:
```ruby
def foo
  bar do
    puts "hello"
  end
end
```
When I paste that into a emacs buffer (with ruby-end block enabled), it pastes this:
```
    def foo
        bar do
          puts "hello"
        end
    end
        end

end
```

The last 2 ends didnt come from the clipboard, but seems like ruby-end still adds them, even if they were not necessary.

**Comment by rejeep** [comment]
Weird, That only happens in the terminal for some reason. Same for you?

**Comment by arthurnn** [comment]
yeah. I only use the terminal. Didnt test on the emacs osx GUI.

**Comment by rejeep** [comment]
Seems I already got a similar issue for another package of mine some time ago. See https://github.com/rejeep/enclose.el/issues/4#issuecomment-2673648

**Comment by arthurnn** [comment]
Yeah, that explanation make sense. I am wondering tho, if we could delay the autocomplete function a bit, to solve this.. Not sure if that would fix, but some ideas around that.

**Comment by rejeep** [comment]
Just thinking, what happens if you use `clipboard-yank` instead of `C-v/M-v` or similar? Same behaviour?

**Comment by arthurnn** [comment]
`clipboard-yank` works.

**Comment by arthurnn** [comment]
yeah.. thats great. I think this solved the problem indeed.. will use the yank commands instead.
thanks :tada:

**Comment by rejeep** [comment]
Glad we sorted that out! :smile:
