### ISSUE TITLE
Typing certain keywords in a commented line inserts an "end"

### ISSUE THREAD

**Issue by dseevr** [rejeep/ruby-end.el#15]
First of all, thanks for this script.

I have a suggestion for an improvement.  I was typing a comment earlier today and noticed that certain keywords (e.g., `for`, `do`, etc.) result in an "end" being inserted.  Example:

<img width="240" alt="screen shot 2017-03-08 at 12 41 52" src="https://cloud.githubusercontent.com/assets/97581/23723084/a928c85e-03fc-11e7-932e-8ecfc3fdd788.png">

I don't think I know enough Lisp to solve this in an acceptable way since a complete solution would need to handle both single line (`#`) and multi-line (`=begin` + `=end`) comments.

**Comment by dgutov** [comment]
> a complete solution would need to handle both single line (#) and multi-line (=begin + =end) comments

If you were looking to submit a patch, the above condition should look like `(not (nth 8 (syntax-ppss)))`.

**Comment by dgutov** [comment]
This problem might also be specific to the major mode (`enh-ruby-mode`?). I can't repro it with `ruby-mode`.

But the fix would be the same: to use `syntax-ppss` in `ruby-end-code-at-point-p`.

**Comment by dgutov** [comment]
That only took 5 years.
